#' Plug-in update of beta prior under binomial likelihood.
#'
#' @param par_prior_beta List-type object, with elements "a" and "b" for beta prior parameters.
#' @param D Vector of 0-1 data (generated by binomial likelihood function).
#'
#' @return List with beta posterior parameters.
#' @export

plugin_posterior_beta_binomial <- function(par_prior_beta, D) {

  #for one presentation of beta-binomial posterior's explicit form,
  #see Kevin Murphy's 'Probabilistic Machine Learning'
  N1 <- sum(D)
  N0 <- length(D) - N1

  par_posterior <- data.frame("point_prb" = N1 / length(D),
                              "a" = N1 + par_prior_beta$a,
                              "b" = N0 + par_prior_beta$b)
  par_posterior

}
